In [1]:
import json
import requests
import flickrapi
import pandas as pd
from tqdm import tqdm
from vincenty import vincenty
import matplotlib.pyplot as plt
import time
import numpy as np

In [2]:
api_key = u'b766ae533b2843f748b174f53885eee4'
api_secret = u'ac3884caa9690723'

In [3]:
flickr = flickrapi.FlickrAPI(api_key, api_secret, format='json')

In [4]:
min_lat = 59.800
max_lat = 69.910

# for Veronica
min_lon = 20.410
max_lon = 25.410


# for Ashish
#min_lon = 25.410
#max_lon = 30.410

n_lat = 6
n_lon = 2

start_lat = min_lat
start_lon = min_lon

lats = np.arange(min_lat, max_lat, (max_lat-min_lat)/n_lat)
lons = np.arange(min_lon, max_lon, (max_lon-min_lon)/n_lon)

bboxes = []

for i_lat, lat in enumerate(lats):
    if  (i_lat + 1 == n_lat):
        end_lat = max_lat
    else:
        end_lat = lats[i_lat+1]
            
    for i_lon, lon in enumerate(lons):
        if (i_lon + 1 == n_lon):
            end_lon = max_lon
        else:
            end_lon = lons[i_lon+1]
        
        bbox = (lon, lat, end_lon, end_lat)
        bboxes.append(bbox)

print(bboxes)
print(len(bboxes))

[(20.41, 59.8, 22.91, 61.485), (22.91, 59.8, 25.41, 61.485), (20.41, 61.485, 22.91, 63.17), (22.91, 61.485, 25.41, 63.17), (20.41, 63.17, 22.91, 64.855), (22.91, 63.17, 25.41, 64.855), (20.41, 64.855, 22.91, 66.54), (22.91, 64.855, 25.41, 66.54), (20.41, 66.54, 22.91, 68.22500000000001), (22.91, 66.54, 25.41, 68.22500000000001), (20.41, 68.22500000000001, 22.91, 69.91), (22.91, 68.22500000000001, 25.41, 69.91)]
12


In [5]:
flickr = flickrapi.FlickrAPI(api_key, api_secret, format='json')
photos = flickr.photos.search(per_page='250', bbox='20.410, 59.800, 30.920, 69.910', has_geo=1)
parsed = json.loads(photos.decode('utf-8'))

print(parsed)

id = parsed['photos']['photo'][0]['id']
geo = flickr.do_flickr_call('flickr.photos.geo.getLocation', photo_id=id)
geo_parsed = json.loads(geo.decode('utf-8'))
print(geo_parsed)
if 'locality' in geo_parsed['photo']['location']:
    print(geo_parsed['photo']['location']['locality']['_content'])
else:
    print('Unknown')


{'photos': {'page': 1, 'pages': 933, 'perpage': 250, 'total': '233224', 'photo': [{'id': '50991982323', 'owner': '63796798@N00', 'secret': '516cebe7e0', 'server': '65535', 'farm': 66, 'title': 'Tukkutori', 'ispublic': 1, 'isfriend': 0, 'isfamily': 0}, {'id': '50992666801', 'owner': '63796798@N00', 'secret': '033c679dac', 'server': '65535', 'farm': 66, 'title': 'There is no way to peace, peace is the way', 'ispublic': 1, 'isfriend': 0, 'isfamily': 0}, {'id': '50992084416', 'owner': '16391511@N00', 'secret': 'f513ac14b2', 'server': '65535', 'farm': 66, 'title': 'Ice-Covered Taivallahti', 'ispublic': 1, 'isfriend': 0, 'isfamily': 0}, {'id': '50990491786', 'owner': '70192309@N03', 'secret': 'e3d7c6bf4a', 'server': '65535', 'farm': 66, 'title': 'Lightroom-852', 'ispublic': 1, 'isfriend': 0, 'isfamily': 0}, {'id': '50990264196', 'owner': '91977610@N00', 'secret': 'a39ae4fc18', 'server': '65535', 'farm': 66, 'title': "St. Isaac's Cathedral", 'ispublic': 1, 'isfriend': 0, 'isfamily': 0}, {'id'

In [10]:
photos_set = []
for b in tqdm(bboxes:
    # Let's count the pages!
    bbox = '{}, {}, {}, {}'.format(b[0], b[1], b[2], b[3])
    res = flickr.photos.search(per_page='250', bbox=bbox, has_geo=1)
    parsed = json.loads(res.decode('utf-8'))
    pages = int(parsed['photos']['pages'])
    print(bbox)
    for page in tqdm(range(1, 2)):
        res = flickr.photos.search(page=page, per_page='250', bbox=bbox, has_geo=1)
        parsed = json.loads(res.decode('utf-8'))
        for p in parsed['photos']['photo']:
            photos_set.append(p)


  0%|                                                                                                                                                                                                                                                | 0/1 [00:00<?, ?it/s]

20.41, 59.8, 22.91, 61.485


  0%|                                                                                                                                                                                                                                                | 0/1 [00:00<?, ?it/s]

22.91, 59.8, 25.41, 61.485


  0%|                                                                                                                                                                                                                                                | 0/1 [00:00<?, ?it/s]

20.41, 61.485, 22.91, 63.17


  0%|                                                                                                                                                                                                                                                | 0/1 [00:00<?, ?it/s]

22.91, 61.485, 25.41, 63.17


  0%|                                                                                                                                                                                                                                                | 0/1 [00:00<?, ?it/s]

20.41, 63.17, 22.91, 64.855


  0%|                                                                                                                                                                                                                                                | 0/1 [00:00<?, ?it/s]

22.91, 63.17, 25.41, 64.855


  0%|                                                                                                                                                                                                                                                | 0/1 [00:00<?, ?it/s]

20.41, 64.855, 22.91, 66.54


  0%|                                                                                                                                                                                                                                                | 0/1 [00:00<?, ?it/s]

22.91, 64.855, 25.41, 66.54


  0%|                                                                                                                                                                                                                                                | 0/1 [00:00<?, ?it/s]

20.41, 66.54, 22.91, 68.22500000000001


  0%|                                                                                                                                                                                                                                                | 0/1 [00:00<?, ?it/s]

22.91, 66.54, 25.41, 68.22500000000001


  0%|                                                                                                                                                                                                                                                | 0/1 [00:00<?, ?it/s]

20.41, 68.22500000000001, 22.91, 69.91


  0%|                                                                                                                                                                                                                                                | 0/1 [00:00<?, ?it/s]

22.91, 68.22500000000001, 25.41, 69.91


100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.26it/s]


In [11]:
len(photos_set)

2763

In [12]:
photos_set[0]

{'id': '50988488177',
 'owner': '41505253@N00',
 'secret': '009ab112e5',
 'server': '65535',
 'farm': 66,
 'title': 'Late winter 2020-21',
 'ispublic': 1,
 'isfriend': 0,
 'isfamily': 0}

In [56]:
# photo_id, lat, lon, name, locality, neighbourhood
photo_ids = []
lats = []
longs = []
names = []
localities = []
neighbourhoods = []
regions = []
for p in tqdm(photos_set):
    photo_id = p['id']
    geo = flickr.do_flickr_call('flickr.photos.geo.getLocation', photo_id=photo_id)
    parsed = json.loads(geo.decode('utf-8'))
    ## construct arrays of data
    photo_ids.append(photo_id)
    names.append(p['title'])
    lats.append(parsed['photo']['location']['latitude'])
    longs.append(parsed['photo']['location']['longitude'])
    neighbourhoods.append(parsed['photo']['location']['neighbourhood']['_content'])
    if 'locality' in parsed['photo']['location']:
        localities.append(parsed['photo']['location']['locality']['_content'])
    else:
        localities.append('Unknown')
    if 'region' in parsed['photo']['location']:
        regions.append(parsed['photo']['location']['region']['_content'])
    else:
        regions.append('Unknown')

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2548/2548 [09:09<00:00,  4.64it/s]


## Data collection strategy:
We collect geographical information on all pictures taken in Finland inside the BBOX 20.410, 59.800, 30.920, 69.910.
Then, we test various clusterization algorithms to create ~500 nodes where each node represents a location.
For each location we can find ot the number of pictures taken, the most common names and tags. 
The edge is represented by distance calculated with Vincenty formula.
UPD We look into whole Europe (bbox is -25.31, 35.17, 40.96, 71.33)

In [58]:
df = pd.DataFrame({'id': photo_ids,
                  'name': names,
                  'lat': lats,
                  'lon': longs,
                  'locality': localities,
                  'region': regions,
                  'neighbourhood': neighbourhoods})

In [59]:
df.to_csv('photoset36-48.csv', index=False)

In [60]:
df2_12 = pd.read_csv('photoset2-12.csv')

df12_24 = pd.read_csv('photoset12-24.csv')

df24_36 = pd.read_csv('photoset24-36.csv')

df36_48 = pd.read_csv('photoset36-48.csv')

df = df2_12.append(df12_24).append(df24_36).append(df36_48)

In [61]:
duplicateRowsDF = df[df.duplicated()]
print(len(df))
len(duplicateRowsDF)

9908


6256

In [ ]:
gdf = geopandas.GeoDataFrame(
    df, geometry=geopandas.points_from_xy(df.lon, df.lat))

In [ ]:
world = geopandas.read_file(geopandas.datasets.get_path('naturalearth_lowres'), bbox=(20.410, 59.800, 30.920, 69.910))

ax = world[world.name == 'Finland'].plot(figsize=(10, 10),
    color='white', edgecolor='black')
ctx.add_basemap(ax)
gdf.plot(ax=ax, alpha=0.5, edgecolor='k')

plt.show()